### CREATE PRODUCT
POST http://localhost:4000/products/create
Content-Type: application/json

{
    "productId":"P101",
    "productName":"Laptop",
    "price":45000,
    "brand":"Dell"
}

### GET ALL PRODUCTS
GET http://localhost:4000/products

### GET PRODUCT BY ID
GET http://localhost:4000/products/69b204db3df2d0f744a99bad

### UPDATE PRODUCT
PUT http://localhost:4000/products/P101
Content-Type: application/json

{
    "price":42000,
    "brand":"Hp"

}

### DELETE PRODUCT
DELETE http://localhost:4000/products/P101
